package io.openim.core.network.gob

import io.openim.core.network.FrameCodec
import io.openim.core.network.GeneralWsReq
import io.openim.core.network.GeneralWsResp

/**
 * Codec for the websocket envelope used by the Go SDK
 * (internal/interaction/encoder.go + long_conn_mgr.go):
 *
 *   outbound: gob(GeneralWsReq)  -> [gzip] -> binary frame
 *   inbound:  binary frame -> [gunzip] -> gob(GeneralWsResp)
 *
 * The Go side creates a fresh `gob.Encoder` per frame, so every frame is a
 * self-contained gob stream: one type-definition message followed by one
 * value message. That makes the type-definition bytes a constant prefix,
 * which this codec replays verbatim (generated by tools/gobgolden and
 * verified byte-identical to Go's output by the golden tests). Decoding
 * never assumes type IDs — definition messages (negative ID) are skipped by
 * their length prefix, because the server assigns IDs from its own
 * process-global registry.
 */
class GobFrameCodec(
    private val compression: Boolean = false,
    private val gzip: Gzip = Gzip,
) : FrameCodec {

    override fun encode(req: GeneralWsReq): ByteArray {
        val w = GobWriter()
        w.beginStruct()
        w.intField(0, req.reqIdentifier.toLong())
        w.stringField(1, req.token)
        w.stringField(2, req.sendID)
        w.stringField(3, req.operationID)
        w.stringField(4, req.msgIncr)
        w.bytesField(5, req.data)
        val value = w.endStruct(REQ_STRUCT_TYPE_ID)
        val frame = REQ_TYPEDEF_PREFIX + value
        return if (compression) gzip.compress(frame) else frame
    }

    override fun decode(payload: ByteArray): GeneralWsResp {
        val raw = if (compression) gzip.decompress(payload) else payload
        val r = GobReader(raw)
        val fields = r.readValueMessage(RESP_LAYOUT)
        return GeneralWsResp(
            reqIdentifier = (fields.ints[0] ?: 0L).toInt(),
            errCode = (fields.ints[1] ?: 0L).toInt(),
            errMsg = fields.strings[2] ?: "",
            msgIncr = fields.strings[3] ?: "",
            operationID = fields.strings[4] ?: "",
            data = fields.bytes[5] ?: ByteArray(0),
        )
    }

    /** Used by tests and the replay harness to act as the server side. */
    fun encodeResp(resp: GeneralWsResp): ByteArray {
        val w = GobWriter()
        w.beginStruct()
        w.intField(0, resp.reqIdentifier.toLong())
        w.intField(1, resp.errCode.toLong())
        w.stringField(2, resp.errMsg)
        w.stringField(3, resp.msgIncr)
        w.stringField(4, resp.operationID)
        w.bytesField(5, resp.data)
        val value = w.endStruct(RESP_STRUCT_TYPE_ID)
        return RESP_TYPEDEF_PREFIX + value
    }

    /** Used by tests and the replay harness to act as the server side. */
    fun decodeReq(payload: ByteArray): GeneralWsReq {
        val fields = GobReader(payload).readValueMessage(REQ_LAYOUT)
        return GeneralWsReq(
            reqIdentifier = (fields.ints[0] ?: 0L).toInt(),
            token = fields.strings[1] ?: "",
            sendID = fields.strings[2] ?: "",
            operationID = fields.strings[3] ?: "",
            msgIncr = fields.strings[4] ?: "",
            data = fields.bytes[5] ?: ByteArray(0),
        )
    }

    companion object {
        /**
         * Type-definition prefixes captured from Go (tools/gobgolden, see
         * kmp/core/testdata/gob-golden.txt). IDs 64/65 match the Go SDK
         * process, where GeneralWsReq is registered first.
         */
        private val REQ_TYPEDEF_PREFIX = (
            "657f0301010c47656e6572616c577352657101ff80000106010d5265714964656e7469666965720104000105546f6b656e010c0001" +
                "0653656e644944010c00010b4f7065726174696f6e4944010c0001074d7367496e6372010c00010444617461010a000000"
            ).hexToBytes()
        private const val REQ_STRUCT_TYPE_ID = 64L

        private val RESP_TYPEDEF_PREFIX = (
            "69ff810301010d47656e6572616c57735265737001ff82000106010d5265714964656e7469666965720104000107457272436f6465" +
                "01040001064572724d7367010c0001074d7367496e6372010c00010b4f7065726174696f6e4944010c00010444617461010a000000"
            ).hexToBytes()
        private const val RESP_STRUCT_TYPE_ID = 65L

        private val REQ_LAYOUT = listOf(
            GobReader.FieldKind.INT,    // ReqIdentifier
            GobReader.FieldKind.STRING, // Token
            GobReader.FieldKind.STRING, // SendID
            GobReader.FieldKind.STRING, // OperationID
            GobReader.FieldKind.STRING, // MsgIncr
            GobReader.FieldKind.BYTES,  // Data
        )
        private val RESP_LAYOUT = listOf(
            GobReader.FieldKind.INT,    // ReqIdentifier
            GobReader.FieldKind.INT,    // ErrCode
            GobReader.FieldKind.STRING, // ErrMsg
            GobReader.FieldKind.STRING, // MsgIncr
            GobReader.FieldKind.STRING, // OperationID
            GobReader.FieldKind.BYTES,  // Data
        )
    }
}

internal fun String.hexToBytes(): ByteArray {
    require(length % 2 == 0) { "odd hex length" }
    return ByteArray(length / 2) { i ->
        ((this[2 * i].digitToInt(16) shl 4) or this[2 * i + 1].digitToInt(16)).toByte()
    }
}

internal fun ByteArray.toHex(): String = joinToString("") {
    (it.toInt() and 0xff).toString(16).padStart(2, '0')
}

/**
 * Writer for one gob struct value message. Field encoding rules
 * (encoding/gob): fields are (delta, value) pairs in increasing field order,
 * zero-valued fields are omitted, and 0x00 terminates the struct.
 */
internal class GobWriter {
    private val body = ArrayList<Byte>(64)
    private var lastField = -1

    fun beginStruct() {
        body.clear()
        lastField = -1
    }

    fun intField(index: Int, value: Long) {
        if (value == 0L) return
        delta(index)
        writeSignedInt(body, value)
    }

    fun stringField(index: Int, value: String) {
        if (value.isEmpty()) return
        delta(index)
        val bytes = value.encodeToByteArray()
        writeUnsignedInt(body, bytes.size.toLong())
        bytes.forEach { body.add(it) }
    }

    fun bytesField(index: Int, value: ByteArray) {
        if (value.isEmpty()) return
        delta(index)
        writeUnsignedInt(body, value.size.toLong())
        value.forEach { body.add(it) }
    }

    /** Returns the complete length-prefixed value message. */
    fun endStruct(structTypeId: Long): ByteArray {
        body.add(0) // end of struct
        val payload = ArrayList<Byte>(body.size + 4)
        writeSignedInt(payload, structTypeId)
        payload.addAll(body)
        val out = ArrayList<Byte>(payload.size + 4)
        writeUnsignedInt(out, payload.size.toLong())
        out.addAll(payload)
        return out.toByteArray()
    }

    private fun delta(index: Int) {
        require(index > lastField) { "fields must be written in order" }
        writeUnsignedInt(body, (index - lastField).toLong())
        lastField = index
    }

    companion object {
        fun writeUnsignedInt(out: MutableList<Byte>, value: Long) {
            if (value in 0..0x7f) {
                out.add(value.toByte())
                return
            }
            var n = 0
            var v = value
            val bytes = ByteArray(8)
            while (v != 0L) {
                bytes[7 - n] = (v and 0xff).toByte()
                v = v ushr 8
                n++
            }
            out.add((-n).toByte())
            for (i in (8 - n) until 8) out.add(bytes[i])
        }

        fun writeSignedInt(out: MutableList<Byte>, value: Long) {
            val u = if (value < 0) (value.inv() shl 1) or 1L else value shl 1
            writeUnsignedInt(out, u)
        }
    }
}

/** Reader over a self-contained gob stream of length-prefixed messages. */
internal class GobReader(private val data: ByteArray) {
    private var pos = 0

    class StructFields {
        val ints = mutableMapOf<Int, Long>()
        val strings = mutableMapOf<Int, String>()
        val bytes = mutableMapOf<Int, ByteArray>()
    }

    enum class FieldKind { INT, STRING, BYTES }

    /**
     * Skips type-definition messages (negative type ID) and decodes the first
     * value message as a struct. The gob value message does not declare field
     * kinds, so the caller supplies the struct layout (field index -> kind).
     */
    fun readValueMessage(kinds: List<FieldKind>): StructFields {
        while (pos < data.size) {
            val msgLen = readUnsignedInt().toInt()
            val msgEnd = pos + msgLen
            require(msgEnd <= data.size) { "truncated gob message" }
            val typeId = readSignedInt()
            if (typeId < 0) { // type definition: skip
                pos = msgEnd
                continue
            }
            val fields = StructFields()
            var field = -1
            while (true) {
                val delta = readUnsignedInt().toInt()
                if (delta == 0) break
                field += delta
                require(field < kinds.size) { "unexpected gob field $field" }
                when (kinds[field]) {
                    FieldKind.INT -> fields.ints[field] = readSignedInt()
                    FieldKind.STRING -> fields.strings[field] = readBytes().decodeToString()
                    FieldKind.BYTES -> fields.bytes[field] = readBytes()
                }
            }
            require(pos == msgEnd) { "gob value message length mismatch" }
            return fields
        }
        throw IllegalStateException("no value message in gob stream")
    }

    fun readUnsignedInt(): Long {
        val b = data[pos].toInt() and 0xff
        pos++
        if (b <= 0x7f) return b.toLong()
        val n = 256 - b
        require(n in 1..8) { "invalid gob uint byte count: $n" }
        var v = 0L
        repeat(n) {
            v = (v shl 8) or (data[pos].toLong() and 0xff)
            pos++
        }
        return v
    }

    fun readSignedInt(): Long {
        val u = readUnsignedInt()
        return if (u and 1L != 0L) (u ushr 1).inv() else u ushr 1
    }

    fun readBytes(): ByteArray {
        val len = readUnsignedInt().toInt()
        val out = data.copyOfRange(pos, pos + len)
        pos += len
        return out
    }
}

/** Cross-platform gzip, mirroring internal/interaction/compressor.go. */
expect object Gzip {
    fun compress(data: ByteArray): ByteArray
    fun decompress(data: ByteArray): ByteArray
}
