// Package main generates the ground-truth SQLite schema produced by the Go
// SDK's GORM AutoMigrate path (see pkg/db/db_init.go versionDataMigrate).
//
// It is used to keep the Kotlin Multiplatform port's SQLDelight schema
// byte-compatible with databases written by this SDK, so upgraded apps keep
// their local data. Run:
//
//	go run ./tools/schemagen [output.sql]
//
// The output is the exact DDL (sqlite_master.sql) for every table and index,
// in deterministic order.
package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/openimsdk/openim-sdk-core/v3/pkg/db/model_struct"

	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

func main() {
	tmpDir, err := os.MkdirTemp("", "schemagen")
	if err != nil {
		panic(err)
	}
	defer os.RemoveAll(tmpDir)

	db, err := gorm.Open(sqlite.Open(filepath.Join(tmpDir, "schema.db")), &gorm.Config{
		Logger: logger.Default.LogMode(logger.Silent),
	})
	if err != nil {
		panic(err)
	}

	// Same model set and order as pkg/db/db_init.go versionDataMigrate.
	if err := db.AutoMigrate(
		&model_struct.LocalAppSDKVersion{},
		&model_struct.LocalFriend{},
		&model_struct.LocalGroup{},
		&model_struct.LocalGroupMember{},
		&model_struct.LocalUser{},
		&model_struct.LocalBlack{},
		&model_struct.LocalConversation{},
		&model_struct.NotificationSeqs{},
		&model_struct.LocalChatLog{},
		&model_struct.LocalChatLogReactionExtensions{},
		&model_struct.LocalUpload{},
		&model_struct.LocalStranger{},
		&model_struct.LocalSendingMessages{},
		&model_struct.LocalVersionSync{},
	); err != nil {
		panic(err)
	}

	type row struct {
		Type string
		Name string
		SQL  string
	}
	var rows []row
	if err := db.Raw(
		`SELECT type, name, COALESCE(sql, '') AS sql FROM sqlite_master
		 WHERE name NOT LIKE 'sqlite_%' ORDER BY type DESC, name`,
	).Scan(&rows).Error; err != nil {
		panic(err)
	}

	out := os.Stdout
	if len(os.Args) > 1 {
		f, err := os.Create(os.Args[1])
		if err != nil {
			panic(err)
		}
		defer f.Close()
		out = f
	}

	fmt.Fprintln(out, "-- Generated by tools/schemagen. Do not edit by hand.")
	fmt.Fprintln(out, "-- Ground-truth SQLite schema written by the Go SDK (GORM AutoMigrate).")
	for _, r := range rows {
		if r.SQL == "" { // auto indexes have no SQL
			continue
		}
		fmt.Fprintf(out, "\n-- %s %s\n%s;\n", r.Type, r.Name, r.SQL)
	}
}
