-- Generated by tools/schemagen. Do not edit by hand.
-- Ground-truth SQLite schema written by the Go SDK (GORM AutoMigrate).

-- table local_app_sdk_version
CREATE TABLE `local_app_sdk_version` (`version` varchar(255),`installed` numeric,PRIMARY KEY (`version`));

-- table local_blacks
CREATE TABLE `local_blacks` (`owner_user_id` varchar(64),`block_user_id` varchar(64),`nickname` varchar(255),`face_url` varchar(255),`create_time` integer,`add_source` integer,`operator_user_id` varchar(64),`ex` varchar(1024),`attached_info` varchar(1024),PRIMARY KEY (`owner_user_id`,`block_user_id`));

-- table local_chat_log_reaction_extensions
CREATE TABLE `local_chat_log_reaction_extensions` (`client_msg_id` char(64),`local_reaction_extensions` blob,PRIMARY KEY (`client_msg_id`));

-- table local_chat_logs
CREATE TABLE `local_chat_logs` (`client_msg_id` char(64),`server_msg_id` char(64),`send_id` char(64),`recv_id` char(64),`sender_platform_id` integer,`sender_nick_name` varchar(255),`sender_face_url` varchar(255),`session_type` integer,`msg_from` integer,`content_type` integer,`content` varchar(1000),`is_read` numeric,`status` integer,`seq` integer DEFAULT 0,`send_time` integer,`create_time` integer,`attached_info` varchar(1024),`ex` varchar(1024),`local_ex` varchar(1024),PRIMARY KEY (`client_msg_id`));

-- table local_conversations
CREATE TABLE `local_conversations` (`conversation_id` char(128),`conversation_type` integer,`user_id` char(64),`group_id` char(128),`show_name` varchar(255),`face_url` varchar(255),`recv_msg_opt` integer,`unread_count` integer,`group_at_type` integer,`latest_msg` varchar(1000),`latest_msg_send_time` integer,`draft_text` text,`draft_text_time` integer,`is_pinned` numeric,`is_private_chat` numeric,`burn_duration` integer DEFAULT 30,`is_not_in_group` numeric,`update_unread_count_time` integer,`attached_info` varchar(1024),`ex` varchar(1024),`max_seq` integer,`min_seq` integer,`msg_destruct_time` integer DEFAULT 604800,`is_msg_destruct` numeric DEFAULT false,PRIMARY KEY (`conversation_id`));

-- table local_friends
CREATE TABLE `local_friends` (`owner_user_id` varchar(64),`friend_user_id` varchar(64),`remark` varchar(255),`create_time` integer,`add_source` integer,`operator_user_id` varchar(64),`name` varchar(255),`face_url` varchar(255),`ex` varchar(1024),`attached_info` varchar(1024),`is_pinned` numeric,PRIMARY KEY (`owner_user_id`,`friend_user_id`));

-- table local_group_members
CREATE TABLE `local_group_members` (`group_id` varchar(64),`user_id` varchar(64),`nickname` varchar(255),`user_group_face_url` varchar(255),`role_level` integer,`join_time` integer,`join_source` integer,`inviter_user_id` text,`mute_end_time` integer DEFAULT 0,`operator_user_id` varchar(64),`ex` varchar(1024),`attached_info` varchar(1024),PRIMARY KEY (`group_id`,`user_id`));

-- table local_groups
CREATE TABLE `local_groups` (`group_id` varchar(64),`name` text,`notification` varchar(255),`introduction` varchar(255),`face_url` varchar(255),`create_time` integer,`status` integer,`creator_user_id` varchar(64),`group_type` integer,`owner_user_id` varchar(64),`member_count` integer,`ex` varchar(1024),`attached_info` varchar(1024),`need_verification` integer,`look_member_info` integer,`apply_member_friend` integer,`notification_update_time` integer,`notification_user_id` text,PRIMARY KEY (`group_id`));

-- table local_notification_seqs
CREATE TABLE `local_notification_seqs` (`conversation_id` char(128),`seq` integer,PRIMARY KEY (`conversation_id`));

-- table local_sending_messages
CREATE TABLE `local_sending_messages` (`conversation_id` char(128),`client_msg_id` char(64),`ex` varchar(1024),PRIMARY KEY (`conversation_id`,`client_msg_id`));

-- table local_stranger
CREATE TABLE `local_stranger` (`user_id` varchar(64),`name` varchar(255),`face_url` varchar(255),`create_time` integer,`app_manger_level` integer,`ex` varchar(1024),`attached_info` varchar(1024),`global_recv_msg_opt` integer,PRIMARY KEY (`user_id`));

-- table local_sync_version
CREATE TABLE `local_sync_version` (`table_name` varchar(255),`entity_id` varchar(255),`version_id` text,`version` integer,`create_time` integer,`id_list` text,PRIMARY KEY (`table_name`,`entity_id`));

-- table local_uploads
CREATE TABLE `local_uploads` (`part_hash` text,`upload_id` varchar(1000),`upload_info` varchar(2000),`expire_time` integer,`create_time` integer,PRIMARY KEY (`part_hash`));

-- table local_users
CREATE TABLE `local_users` (`user_id` varchar(64),`name` varchar(255),`face_url` varchar(255),`create_time` integer,`app_manger_level` integer,`ex` varchar(1024),`attached_info` varchar(1024),`global_recv_msg_opt` integer,PRIMARY KEY (`user_id`));

-- index content_type_alone
CREATE INDEX `content_type_alone` ON `local_chat_logs`(`content_type`);

-- index index_join_time
CREATE INDEX `index_join_time` ON `local_group_members`(`join_time`);

-- index index_latest_msg_send_time
CREATE INDEX `index_latest_msg_send_time` ON `local_conversations`(`latest_msg_send_time`);

-- index index_recv_id
CREATE INDEX `index_recv_id` ON `local_chat_logs`(`recv_id`);

-- index index_role_level
CREATE INDEX `index_role_level` ON `local_group_members`(`role_level`);

-- index index_send_time
CREATE INDEX `index_send_time` ON `local_chat_logs`(`send_time`);

-- index index_seq
CREATE INDEX `index_seq` ON `local_chat_logs`(`seq`);
