package io.openim.core.network.gob

import io.openim.core.network.GeneralWsReq
import io.openim.core.network.GeneralWsResp
import java.io.File
import kotlin.test.Test
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * Full golden-vector suite generated by Go's own gob encoder
 * (tools/gobgolden → testdata/gob-golden.txt): the Kotlin codec must be
 * byte-identical on encode and decode Go's output, and gzip must interop
 * with Go compress/gzip.
 */
class GobGoldenTest {

    private val codec = GobFrameCodec(compression = false)

    @Test
    fun matchesGoGoldenVectors() {
        var req = 0
        var resp = 0
        var gz = 0
        File("testdata/gob-golden.txt").readLines().filter { it.isNotBlank() }.forEach { line ->
            val p = line.split("|")
            when (p[0]) {
                "PREFIX_REQ", "PREFIX_RESP" -> Unit
                "REQ" -> {
                    val msg = GeneralWsReq(p[2].toInt(), p[3], p[4], p[5], p[6], p[7].hexToBytes())
                    assertEquals(p[1], codec.encode(msg).toHex(), "REQ encode for $msg")
                    val decoded = codec.decodeReq(p[1].hexToBytes())
                    assertEquals(msg.reqIdentifier, decoded.reqIdentifier)
                    assertEquals(msg.operationID, decoded.operationID)
                    assertContentEquals(msg.data, decoded.data)
                    req++
                }
                "RESP" -> {
                    val msg = GeneralWsResp(p[2].toInt(), p[3].toInt(), p[4], p[5], p[6], p[7].hexToBytes())
                    assertEquals(p[1], codec.encodeResp(msg).toHex(), "RESP encode for $msg")
                    val decoded = codec.decode(p[1].hexToBytes())
                    assertEquals(msg.errCode, decoded.errCode)
                    assertEquals(msg.errMsg, decoded.errMsg)
                    assertContentEquals(msg.data, decoded.data)
                    resp++
                }
                "GZIP" -> {
                    val raw = p[2].hexToBytes()
                    assertContentEquals(raw, Gzip.decompress(p[1].hexToBytes()))
                    assertContentEquals(raw, Gzip.decompress(Gzip.compress(raw)))
                    gz++
                }
            }
        }
        assertTrue(req >= 5 && resp >= 4 && gz >= 3, "golden file truncated? req=$req resp=$resp gz=$gz")
    }
}
